### PR TITLE
WIP: team page

### PR DESCRIPTION
**Pull request by cwaring**
localhost_3000_team
closes: protocol/2019-ipfs-camp#46

### CODE REVIEW

**Comment by cwaring** [comment]
@daviddias this is now ready to roll, check out [the preview](https://deploy-preview-29--camp-ipfs.netlify.com/team).

**Comment by daviddias** [comment]
Looooking rad!! 

Can we include the Network DRI and Content DRIs to the production team as well? Namely Kuba, Alan, Oli, Dietrich, Dominic, Jessica and Arkadiy?

Also, I'm thinking that having both a section for Trainers and another for Speakers might be good. Some people will appear twice but that is good because it is a way to recognize the double of the effort they are putting in.

**Comment by daviddias** [comment]
Btw, seems that names are all mixed up

image

**Comment by cwaring** [comment]
yep just noticed that, fixing now. seems I can't sort without forcing a re-render at the comp level.

**Comment by cwaring** [comment]
> Looooking rad!!
> 
> Can we include the Network DRI and Content DRIs to the production team as well? Namely Kuba, Alan, Oli, Dietrich, Dominic, Jessica and Arkadiy?
> 

Np, I need to do a final pass and the additional people into the core team.

> Also, I'm thinking that having both a section for Trainers and another for Speakers might be good. Some people will appear twice but that is good because it is a way to recognize the double of the effort they are putting in.

At this stage I'd rather keep everyone grouped together to save repetition and add the additional context via the schedule once the content is loaded in.

**Comment by daviddias** [comment]
> At this stage I'd rather keep everyone grouped

Would there be a next stage in which we can separate and then create sections for the Champions of the Poster Projects, Deep Dives and Sci-Fi fair project demoers?

**Comment by cwaring** [comment]
> Would there be a next stage in which we can separate and then create sections for the Champions of the Poster Projects, Deep Dives and Sci-Fi fair project demoers?

Yes you will see this on the schedule page when individuals are assigned to certain types of content. Also after the event we could create pages for each contributor so you can see what sessions they produced alongside the videos and/or downloadable material. I have all the plans if scope permits :)

**Comment by daviddias** [comment]
Sounds good then. So the plan is to get this one merged right now?

**Comment by cwaring** [comment]
@daviddias yes, once I've checked over the contributor list this will be deployed

**Comment by jessicaschilling** [comment]
@cwaring - sorry to be a pest but Jim McD was last-minute replaced as lightning talk-er by Makoto Inoue (last row on lightning talk speaker grid). Unsure if Jim appears anywhere else as a speaker, but can we please add Makoto or replace for Jim as appropriate? Thank you!

**Comment by cwaring** [comment]
@jessicaschilling no problem, I've added Makoto and I will double check if Jim's contributing to any other sessions during the data load.

**Pull request merged**
